/** Generated by pnpm props:index. Do not edit. */
import cup from "./cup.json";
import baby_bottle from "./drinks/baby-bottle.json";
import bubble_tea from "./drinks/bubble-tea.json";
import energy_drink from "./drinks/energy-drink.json";
import juice_box from "./drinks/juice-box.json";
import milkshake from "./drinks/milkshake.json";
import soda_can from "./drinks/soda-can.json";
import takeaway_coffee from "./drinks/takeaway-coffee.json";
import thermos from "./drinks/thermos.json";
import water_bottle from "./drinks/water-bottle.json";
import water_glass from "./drinks/water-glass.json";
import apple from "./food/apple.json";
import banana from "./food/banana.json";
import burger from "./food/burger.json";
import carrot from "./food/carrot.json";
import chicken_drumstick from "./food/chicken-drumstick.json";
import chocolate_bar from "./food/chocolate-bar.json";
import cookie from "./food/cookie.json";
import croissant from "./food/croissant.json";
import cupcake from "./food/cupcake.json";
import donut from "./food/donut.json";
import fries from "./food/fries.json";
import hot_dog from "./food/hot-dog.json";
import ice_cream_cone from "./food/ice-cream-cone.json";
import noodle_bowl from "./food/noodle-bowl.json";
import pizza_slice from "./food/pizza-slice.json";
import popcorn from "./food/popcorn.json";
import sandwich from "./food/sandwich.json";
import taco from "./food/taco.json";
import alarm_clock from "./home/alarm-clock.json";
import broom from "./home/broom.json";
import hairdryer from "./home/hairdryer.json";
import hand_mirror from "./home/hand-mirror.json";
import keys from "./home/keys.json";
import mop from "./home/mop.json";
import pillow from "./home/pillow.json";
import potted_plant from "./home/potted-plant.json";
import spray_bottle from "./home/spray-bottle.json";
import toilet_roll from "./home/toilet-roll.json";
import toothbrush from "./home/toothbrush.json";
import umbrella from "./home/umbrella.json";
import fork from "./kitchen/fork.json";
import frying_pan from "./kitchen/frying-pan.json";
import oven_mitt from "./kitchen/oven-mitt.json";
import plate from "./kitchen/plate.json";
import rolling_pin from "./kitchen/rolling-pin.json";
import spatula from "./kitchen/spatula.json";
import spoon from "./kitchen/spoon.json";
import whisk from "./kitchen/whisk.json";
import laptop from "./laptop.json";
import mic from "./mic.json";
import cash from "./money/cash.json";
import credit_card from "./money/credit-card.json";
import gift_box from "./money/gift-box.json";
import piggy_bank from "./money/piggy-bank.json";
import receipt from "./money/receipt.json";
import shopping_bag from "./money/shopping-bag.json";
import shopping_basket from "./money/shopping-basket.json";
import wallet from "./money/wallet.json";
import book from "./office/book.json";
import calculator from "./office/calculator.json";
import clipboard from "./office/clipboard.json";
import envelope from "./office/envelope.json";
import folder from "./office/folder.json";
import id_badge from "./office/id-badge.json";
import notebook from "./office/notebook.json";
import pen from "./office/pen.json";
import pencil from "./office/pencil.json";
import pill_bottle from "./office/pill-bottle.json";
import ruler from "./office/ruler.json";
import stapler from "./office/stapler.json";
import balloon from "./party/balloon.json";
import flower_bouquet from "./party/flower-bouquet.json";
import megaphone from "./party/megaphone.json";
import party_popper from "./party/party-popper.json";
import rose from "./party/rose.json";
import small_flag from "./party/small-flag.json";
import sparkler from "./party/sparkler.json";
import phone from "./phone.json";
import sign from "./sign.json";
import basketball from "./sport/basketball.json";
import dumbbell from "./sport/dumbbell.json";
import soccer_ball from "./sport/soccer-ball.json";
import stopwatch from "./sport/stopwatch.json";
import tennis_racket from "./sport/tennis-racket.json";
import trophy from "./sport/trophy.json";
import whistle from "./sport/whistle.json";
import yoga_mat from "./sport/yoga-mat.json";
import camera from "./tech/camera.json";
import charger from "./tech/charger.json";
import computer_mouse from "./tech/computer-mouse.json";
import game_controller from "./tech/game-controller.json";
import headphones from "./tech/headphones.json";
import power_bank from "./tech/power-bank.json";
import selfie_stick from "./tech/selfie-stick.json";
import tablet from "./tech/tablet.json";
import thermometer from "./tech/thermometer.json";
import tv_remote from "./tech/tv-remote.json";
import binoculars from "./travel/binoculars.json";
import fishing_rod from "./travel/fishing-rod.json";
import flashlight from "./travel/flashlight.json";
import paper_map from "./travel/paper-map.json";
import passport from "./travel/passport.json";
import suitcase from "./travel/suitcase.json";
import ticket from "./travel/ticket.json";

export const PROP_DOCS = [
  cup,
  baby_bottle,
  bubble_tea,
  energy_drink,
  juice_box,
  milkshake,
  soda_can,
  takeaway_coffee,
  thermos,
  water_bottle,
  water_glass,
  apple,
  banana,
  burger,
  carrot,
  chicken_drumstick,
  chocolate_bar,
  cookie,
  croissant,
  cupcake,
  donut,
  fries,
  hot_dog,
  ice_cream_cone,
  noodle_bowl,
  pizza_slice,
  popcorn,
  sandwich,
  taco,
  alarm_clock,
  broom,
  hairdryer,
  hand_mirror,
  keys,
  mop,
  pillow,
  potted_plant,
  spray_bottle,
  toilet_roll,
  toothbrush,
  umbrella,
  fork,
  frying_pan,
  oven_mitt,
  plate,
  rolling_pin,
  spatula,
  spoon,
  whisk,
  laptop,
  mic,
  cash,
  credit_card,
  gift_box,
  piggy_bank,
  receipt,
  shopping_bag,
  shopping_basket,
  wallet,
  book,
  calculator,
  clipboard,
  envelope,
  folder,
  id_badge,
  notebook,
  pen,
  pencil,
  pill_bottle,
  ruler,
  stapler,
  balloon,
  flower_bouquet,
  megaphone,
  party_popper,
  rose,
  small_flag,
  sparkler,
  phone,
  sign,
  basketball,
  dumbbell,
  soccer_ball,
  stopwatch,
  tennis_racket,
  trophy,
  whistle,
  yoga_mat,
  camera,
  charger,
  computer_mouse,
  game_controller,
  headphones,
  power_bank,
  selfie_stick,
  tablet,
  thermometer,
  tv_remote,
  binoculars,
  fishing_rod,
  flashlight,
  paper_map,
  passport,
  suitcase,
  ticket,
];

export const PROP_IDS = ["cup", "baby-bottle", "bubble-tea", "energy-drink", "juice-box", "milkshake", "soda-can", "takeaway-coffee", "thermos", "water-bottle", "water-glass", "apple", "banana", "burger", "carrot", "chicken-drumstick", "chocolate-bar", "cookie", "croissant", "cupcake", "donut", "fries", "hot-dog", "ice-cream-cone", "noodle-bowl", "pizza-slice", "popcorn", "sandwich", "taco", "alarm-clock", "broom", "hairdryer", "hand-mirror", "keys", "mop", "pillow", "potted-plant", "spray-bottle", "toilet-roll", "toothbrush", "umbrella", "fork", "frying-pan", "oven-mitt", "plate", "rolling-pin", "spatula", "spoon", "whisk", "laptop", "mic", "cash", "credit-card", "gift-box", "piggy-bank", "receipt", "shopping-bag", "shopping-basket", "wallet", "book", "calculator", "clipboard", "envelope", "folder", "id-badge", "notebook", "pen", "pencil", "pill-bottle", "ruler", "stapler", "balloon", "flower-bouquet", "megaphone", "party-popper", "rose", "small-flag", "sparkler", "phone", "sign", "basketball", "dumbbell", "soccer-ball", "stopwatch", "tennis-racket", "trophy", "whistle", "yoga-mat", "camera", "charger", "computer-mouse", "game-controller", "headphones", "power-bank", "selfie-stick", "tablet", "thermometer", "tv-remote", "binoculars", "fishing-rod", "flashlight", "paper-map", "passport", "suitcase", "ticket"] as const;
