/**
 * Regenerates src/data/props/index.ts from every prop JSON file.
 * A new prop is one file, then `pnpm props:index`.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");

const root = path.join(ROOT, "src/data/props");

const walk = (dir: string): string[] =>
  fs.readdirSync(dir, { withFileTypes: true }).flatMap((ent) => {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) return walk(abs);
    return ent.name.endsWith(".json") ? [abs] : [];
  });

const files = walk(root).sort();
const rows = files.map((abs) => {
  const rel = path.relative(root, abs).replaceAll("\\", "/");
  const id = JSON.parse(fs.readFileSync(abs, "utf8")).id as string;
  const ident = id.replace(/[^a-zA-Z0-9]/g, "_");
  return { rel, id, ident };
});
const body = `/** Generated by pnpm props:index. Do not edit. */\n${rows.map((r) => `import ${r.ident} from "./${r.rel}";`).join("\n")}\n\nexport const PROP_DOCS = [\n${rows.map((r) => `  ${r.ident},`).join("\n")}\n];\n\nexport const PROP_IDS = [${rows.map((r) => JSON.stringify(r.id)).join(", ")}] as const;\n`;
fs.writeFileSync(path.join(root, "index.ts"), body);
console.log(`indexed ${rows.length} props`);
